include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    require_trailing_commas: true
    avoid_void_async: true
    unawaited_futures: true
