name: conference_2023
description: FlutterKaigi 2023 official application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
  flutter: '>=3.12.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2

  # annotation
  freezed_annotation: ^2.0.0
  json_annotation: ^4.0.0
  riverpod_annotation: ^2.0.0

  flutter_riverpod: ^2.0.0
  go_router: ^8.0.0

  gap: ^3.0.0
  flutter_svg: ^2.0.0
  url_launcher: ^6.0.0

  accessibility_tools: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  riverpod_generator: ^2.0.0
  flutter_gen_runner: ^5.0.0
  go_router_builder: ^2.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
