name: confapp2023
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  gap: ^2.0.1
  get_storage: ^2.0.3
  go_router: ^5.2.1
  hooks_riverpod: ^2.1.3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  state_notifier: ^0.7.2+1
  styled_text: ^6.0.0
  transparent_image: ^2.0.0
  webview_flutter: ^4.0.0

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/photo/
