name: conference_2023
description: FlutterKaigi 2023 official application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
  flutter: '>=3.11.0-1.0.pre.1'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
