name: conference_2023
description: FlutterKaigi 2023 official application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'
  flutter: '>=3.11.0-0.1.pre'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # annotation
  freezed_annotation: ^2.0.0
  json_annotation: ^4.0.0
  riverpod_annotation: ^2.0.0

  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.0.0

  build_runner: ^2.0.0
  freezed: ^2.0.0
  json_serializable: ^6.0.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
