name: PR review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v2.0.0

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter test
